#############################################################################
# Generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#  May 26, 2022 09:07:17 AM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m48" -background #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1366x705+-7+17
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab46 \
        \
        -font {-family {Nirmala UI Semilight} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #9dc9f4 -text {Tally Prime} -background #0433d5 \
        -height 65 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 1380 
    vTcl:DefineAlias "$top.lab46" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab46
    label $site_3_0.lab80 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #0433d5 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Tahoma -size 17 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #c0b73f -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text GOLD 
    vTcl:DefineAlias "$site_3_0.lab80" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab81 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #0433d5 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 8 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #55d1e8 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text MANAGE 
    vTcl:DefineAlias "$site_3_0.lab81" "Label8" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but82 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433d5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text K:Company 
    vTcl:DefineAlias "$site_3_0.but82" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but83 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433D5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Y:Data 
    vTcl:DefineAlias "$site_3_0.but83" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but84 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433D5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Z:Exchange 
    vTcl:DefineAlias "$site_3_0.but84" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but85 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {G:Go To} 
    vTcl:DefineAlias "$site_3_0.but85" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but86 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433d5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text O:Import 
    vTcl:DefineAlias "$site_3_0.but86" "Button5" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but87 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433d5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text E:Export 
    vTcl:DefineAlias "$site_3_0.but87" "Button6" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but88 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433d5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text M:E-mail 
    vTcl:DefineAlias "$site_3_0.but88" "Button7" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but89 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433d5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text P:Print 
    vTcl:DefineAlias "$site_3_0.but89" "Button8" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but90 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433d5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text F1:Help 
    vTcl:DefineAlias "$site_3_0.but90" "Button9" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab80 \
        -in $site_3_0 -x 0 -y 0 -rely 0.308 -width 0 -relwidth 0.053 \
        -height 0 -relheight 0.477 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 0 -relx 0.093 -y 0 -width 0 -relwidth 0.062 \
        -height 0 -relheight 0.477 -anchor nw -bordermode ignore 
    place $site_3_0.but82 \
        -in $site_3_0 -x 0 -relx 0.093 -y 0 -rely 0.462 -width 77 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but83 \
        -in $site_3_0 -x 0 -relx 0.203 -y 0 -rely 0.462 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but84 \
        -in $site_3_0 -x 0 -relx 0.304 -y 0 -rely 0.462 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but85 \
        -in $site_3_0 -x 0 -relx 0.406 -y 0 -rely 0.462 -width 77 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but86 \
        -in $site_3_0 -x 0 -relx 0.616 -y 0 -rely 0.462 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but87 \
        -in $site_3_0 -x 0 -relx 0.681 -y 0 -rely 0.462 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but88 \
        -in $site_3_0 -x 0 -relx 0.739 -y 0 -rely 0.462 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but89 \
        -in $site_3_0 -x 0 -relx 0.812 -y 0 -rely 0.462 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but90 \
        -in $site_3_0 -x 0 -relx 0.87 -y 0 -rely 0.462 -width 57 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background #9dc9f4 -height 24 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 1387 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra47
    frame $site_3_0.fra49 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.fra49" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab152 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #9dc9f4 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 8 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Select Group} 
    vTcl:DefineAlias "$site_3_0.lab152" "Label14" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.fra49 \
        -in $site_3_0 -x 0 -relx 0.916 -y 0 -rely 6 -width 0 -relwidth 0.092 \
        -height 0 -relheight 5 -anchor nw -bordermode ignore 
    place $site_3_0.lab152 \
        -in $site_3_0 -x 0 -relx 0.008 -y 0 -width 0 -relwidth 0.096 \
        -height 0 -relheight 0.875 -anchor nw -bordermode ignore 
    menu $top.m48 \
        -activebackground #400000 -activeforeground #000000 \
        -background #ede294 \
        -font {-family {Yu Gothic UI Semibold} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #96ebeb -tearoff 0 
    frame $top.fra121 \
        -borderwidth 2 -relief groove -background #bcf5fa -height 64 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 1233 
    vTcl:DefineAlias "$top.fra121" "Frame5" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra121
    button $site_3_0.but122 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 8 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Q:Quit 
    vTcl:DefineAlias "$site_3_0.but122" "Button12" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but186 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #808080 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text {{}} 
    vTcl:DefineAlias "$site_3_0.but186" "Button28" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but188 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #808080 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {{}} 
    vTcl:DefineAlias "$site_3_0.but188" "Button29" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but189 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Back 
    vTcl:DefineAlias "$site_3_0.but189" "Button30" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but190 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {{}} 
    vTcl:DefineAlias "$site_3_0.but190" "Button31" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but191 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {{}} 
    vTcl:DefineAlias "$site_3_0.but191" "Button30_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but192 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {{}} 
    vTcl:DefineAlias "$site_3_0.but192" "Button30_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but193 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text A:Accept 
    vTcl:DefineAlias "$site_3_0.but193" "Button30_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but194 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {{}} 
    vTcl:DefineAlias "$site_3_0.but194" "Button30_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but195 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {{}} 
    vTcl:DefineAlias "$site_3_0.but195" "Button30_1_1_1_2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but122 \
        -in $site_3_0 -x 0 -relx 0.008 -y 0 -rely 0.135 -width 97 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but186 \
        -in $site_3_0 -x 0 -relx 0.19 -y 0 -rely 0.135 -width 107 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but188 \
        -in $site_3_0 -x 0 -relx 0.775 -y 0 -rely 0.135 -width 117 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but189 \
        -in $site_3_0 -x 0 -relx 0.89 -y 0 -rely 0.135 -width 117 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but190 \
        -in $site_3_0 -x 0 -relx 0.684 -y 0 -rely 0.135 -width 97 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but191 \
        -in $site_3_0 -x 0 -relx 0.585 -y 0 -rely 0.135 -width 97 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but192 \
        -in $site_3_0 -x 0 -relx 0.487 -y 0 -rely 0.135 -width 104 \
        -relwidth 0 -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but193 \
        -in $site_3_0 -x 0 -relx 0.289 -y 0 -rely 0.135 -width 104 \
        -relwidth 0 -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but194 \
        -in $site_3_0 -x 0 -relx 0.373 -y 0 -rely 0.135 -width 104 \
        -relwidth 0 -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but195 \
        -in $site_3_0 -x 0 -relx 0.099 -y 0 -rely 0.135 -width 94 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra48 \
        -relief groove -background #ffffff -height 595 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 1233 
    vTcl:DefineAlias "$top.fra48" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra48
    frame $site_3_0.fra51 \
        -borderwidth 2 -relief groove -background #ffffff -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 247 
    vTcl:DefineAlias "$site_3_0.fra51" "Frame7" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra51
    label $site_4_0.lab52 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #ffffff -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {@Malgun Gothic} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Name of Group} 
    vTcl:DefineAlias "$site_4_0.lab52" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent53 \
        -background #f0f2c6 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground #25aff1 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 184 
    vTcl:DefineAlias "$site_4_0.ent53" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab52 \
        -in $site_4_0 -x 0 -relx 0.283 -y 0 -rely 0.118 -width 0 \
        -relwidth 0.462 -height 0 -relheight 0.247 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent53 \
        -in $site_4_0 -x 0 -relx 0.121 -y 0 -rely 0.533 -width 184 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra55 \
        -borderwidth 2 -relief groove -background #ffffff -height 524 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 314 
    vTcl:DefineAlias "$site_3_0.fra55" "Frame6" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra55
    frame $site_4_0.fra56 \
        -borderwidth 2 -relief groove -background #0433d5 -height 25 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 315 
    vTcl:DefineAlias "$site_4_0.fra56" "Frame8" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.fra56
    label $site_5_0.lab57 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #0433d5 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {List of Groups} 
    vTcl:DefineAlias "$site_5_0.lab57" "Label2" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab57 \
        -in $site_5_0 -x 0 -relx 0.032 -y 0 -width 0 -relwidth 0.552 \
        -height 0 -relheight 0.84 -anchor nw -bordermode ignore 
    button $site_4_0.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor ne -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Create 
    vTcl:DefineAlias "$site_4_0.but58" "Button10" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor sw -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Loans(Liability) 
    vTcl:DefineAlias "$site_4_0.but49" "Button15" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor sw -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Loans & Advances(Asset)} 
    vTcl:DefineAlias "$site_4_0.but50" "Button16" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Investments 
    vTcl:DefineAlias "$site_4_0.but51" "Button17" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Indirect Incomes} 
    vTcl:DefineAlias "$site_4_0.but52" "Button18" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Indirect Expenses} 
    vTcl:DefineAlias "$site_4_0.but53" "Button19" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor sw -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Expenses (Indirect)} 
    vTcl:DefineAlias "$site_4_0.but54" "Button20" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Expenses(Direct) 
    vTcl:DefineAlias "$site_4_0.but55" "Button21" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Duties & Taxes} 
    vTcl:DefineAlias "$site_4_0.but56" "Button22" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Direct Incomes} 
    vTcl:DefineAlias "$site_4_0.but57" "Button23" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Direct Expenses} 
    vTcl:DefineAlias "$site_4_0.but59" "Button24" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Deposits(Asset) 
    vTcl:DefineAlias "$site_4_0.but60" "Button25" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Current Liabilities} 
    vTcl:DefineAlias "$site_4_0.but61" "Button26" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Current Assets} 
    vTcl:DefineAlias "$site_4_0.but62" "Button27" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Cash-in-Hand 
    vTcl:DefineAlias "$site_4_0.but63" "Button32" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Capital Account} 
    vTcl:DefineAlias "$site_4_0.but64" "Button33" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but66 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -anchor sw -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Bank OD A/c} 
    vTcl:DefineAlias "$site_4_0.but66" "Button35" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Bank OCC A/c} 
    vTcl:DefineAlias "$site_4_0.but67" "Button36" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor sw -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Bank Accounts} 
    vTcl:DefineAlias "$site_4_0.but68" "Button37" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Misc. Expenses(ASSET)} 
    vTcl:DefineAlias "$site_4_0.but46" "Button11" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor sw -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Provisions 
    vTcl:DefineAlias "$site_4_0.but47" "Button13" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Purchase Accounts} 
    vTcl:DefineAlias "$site_4_0.but48" "Button14" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor sw -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Reserves & Surplus} 
    vTcl:DefineAlias "$site_4_0.but69" "Button38" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but70 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Retained Earnings} 
    vTcl:DefineAlias "$site_4_0.but70" "Button39" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but71 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor sw -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Sales Accounts} 
    vTcl:DefineAlias "$site_4_0.but71" "Button40" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but72 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor sw -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Secured Loans} 
    vTcl:DefineAlias "$site_4_0.but72" "Button41" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but73 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Stock-in-Hand 
    vTcl:DefineAlias "$site_4_0.but73" "Button42" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but65 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Branch/Divisions 
    vTcl:DefineAlias "$site_4_0.but65" "Button34" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but74 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor sw -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Fixed Assets} 
    vTcl:DefineAlias "$site_4_0.but74" "Button43" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but75 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Indirect(Indirect) 
    vTcl:DefineAlias "$site_4_0.but75" "Button44" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but76 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Income(Direct) 
    vTcl:DefineAlias "$site_4_0.but76" "Button45" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.fra56 \
        -in $site_4_0 -x 0 -y 0 -width 0 -relwidth 1.003 -height 0 \
        -relheight 0.049 -anchor nw -bordermode ignore 
    place $site_4_0.but58 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.097 -width 287 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but49 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.534 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but50 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.496 -width 197 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but51 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.496 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but52 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.477 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but53 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.458 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but54 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.363 -width 197 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but55 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.363 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but56 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.344 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but57 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.324 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but59 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.305 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but60 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.286 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but61 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.267 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but62 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.248 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but63 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.229 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but64 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.21 -width 197 -relwidth 0 \
        -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but66 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.153 -width 197 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but67 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.134 -width 197 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but68 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.119 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but46 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.553 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but47 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.592 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but48 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.611 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but69 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.649 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but70 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.668 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but71 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.725 -width 194 \
        -relwidth 0 -height 9 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but72 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.744 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but73 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.763 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but65 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.191 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but74 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.401 -width 177 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but75 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.439 -width 197 \
        -relwidth 0 -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but76 \
        -in $site_4_0 -x 0 -relx 0.032 -y 0 -rely 0.42 -width 147 -relwidth 0 \
        -height 14 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra51 \
        -in $site_3_0 -x 0 -relx 0.414 -y 0 -width 0 -relwidth 0.2 -height 0 \
        -relheight 0.128 -anchor nw -bordermode ignore 
    place $site_3_0.fra55 \
        -in $site_3_0 -x 0 -relx 0.381 -y 0 -rely 0.118 -width 0 \
        -relwidth 0.255 -height 0 -relheight 0.881 -anchor nw \
        -bordermode ignore 
    frame $top.fra50 \
        -borderwidth 2 -relief groove -background #caffff -height 624 \
        -highlightbackground #ffff00 -highlightcolor black -width 136 
    vTcl:DefineAlias "$top.fra50" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1.01 -height 0 -relheight 0.092 \
        -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -relx -0.007 -y 0 -rely 0.085 -width 0 -relwidth 1.015 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.fra121 \
        -in $top -x 0 -y 0 -rely 0.95 -width 0 -relwidth 0.903 -height 0 \
        -relheight 0.091 -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 0 -y 0 -rely 0.113 -width 0 -relwidth 0.903 -height 0 \
        -relheight 0.844 -anchor nw -bordermode ignore 
    place $top.fra50 \
        -in $top -x 0 -relx 0.9 -y 0 -rely 0.113 -width 0 -relwidth 0.1 \
        -height 0 -relheight 0.885 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

